### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Dmytro-Fedoryshyn** [SchweizerischeBundesbahnen/scion-rcp#85]
I encountered an issue while trying to set up and run your project in Eclipse IDE 2024-09 on Windows 11 with Java 17. Here's what I've done so far:
1. Cloned the project.
2. Installed Lombok, as directed in the README file.
3. Set the MAVEN_OPTS=-javaagent:<path-to-lombok-jar> environment variable.
However, all required dependencies seem to be missing. When I attempt to run `mvn clean install`, I encounter the following exception:
```
Execution default-compile of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:compile failed: A required class was missing while executing org.eclipse.tycho:tycho-compiler-plugin:3.0.4:compile: org/eclipse/jdt/internal/compiler/parser/Parser.
```
@danielwiehl @ruadrian Could you please assist on setting up the project in Eclipse to ensure all required dependencies are correctly resolved?

**Comment by ruadrian** [comment]
Hi Dmytro, which Lombok version did you use?

**Comment by Dmytro-Fedoryshyn** [comment]
@ruadrian I'm sorry for the delay in replying. It turned out that I was using the latest version of Lombok and it was causing this bug. After rolling back to 1.18.26 this bug disappeared. Thank you for you help!
